CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(
  Item_ID      SERIAL      NOT NULL,
  Quantity     INT         NOT NULL,
  Order_Number INT         NOT NULL,
  Product_ID   VARCHAR(20) NOT NULL,
  PRIMARY KEY (Item_ID),
  CONSTRAINT FK FOREIGN KEY (Order_number) REFERENCES ORDERS (Order_number) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK1 FOREIGN KEY (Product_id) REFERENCES PRODUCTS (Product_ID) ON DELETE NO ACTION ON UPDATE CASCADE
)